export const WORDS = [
  'BANANA','CACHORRO','GATO','ELEFANTE','PAPAGAIO','GIRASSOL','MORANGO','CAMINHAO','CARRO','MOTO',
  'BOLA','CAMA','MESA','CADEIRA','GIRAFA','COELHO','PIRULITO','SAPATO','CAMISA','FLORESTA',
  'ESCOLA','LIVRO','COMPUTADOR','TELEFONE','PONTE','CASTELO','OCEANO','LUA','ESTRELA','NUVEM', 'CORREDOR', 'ESCOVA' , 'SALGADO',
  'DOCE', 'PILOTO' , 'COLORIDO', 'PAPEL', 'HOMEM', 'MULHER'
];

export function pickRandomWord() {
  return WORDS[Math.floor(Math.random() * WORDS.length)];
}
